openapi: 3.0.3
info:
  title: OpenAD - Internal API
  description: Internal Open Active Directory API used for API management. THIS API SHOULDN'T BE USED FOR APPS, for that - use the external API.
  version: 1.0.0
tags:
  - name: Auth
    description: Authentication & authorization endpoints for both regular and administrator accounts.
  - name: Public routes
    description: Endpoints used for users to review their data and its usage across apps.
  - name: User management
    description: Endpoints for managing users inside a directory.
  - name: App management
    description: Endpoints for registering, deregistering and managing apps and their app permission scopes.
components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    AuthorizationError:
      required:
        - meta
        - code
      type: object
      properties:
        meta:
          $ref: "#/components/schemas/RequestMeta"
        code:
          type: string
          enum:
            - ERR_AUTHORIZATION
    RequestMeta:
      required:
        - timestamp
        - requestId
      type: object
      properties:
        timestamp:
          type: string
          format: date-time
        requestId:
          type: string
          format: uuid
    TokenPair:
      type: object
      properties:
        access:
          type: string
          format: jwt
          example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c
        refresh:
          type: string
          format: sha256
          example: 2cf24dba5fb0a30e26e83b2ac5b9e29e1b161e5c1fa7425e73043362938b9824
security:
  - BearerAuth: []
servers:
  - url: /api/v1/internal
paths:
  /auth:
    post:
      security: []
      tags:
        - Auth
      summary: Retrieves a new token pair from login credentials.
      description: Accepts user credentials. If valid, returns the authorization token pair.
      requestBody:
        content:
          application/json:
            schema:
              required:
                - username
                - password
              type: object
              properties:
                username:
                  type: string
                  example: john.doe
                password:
                  type: string
                  example: Password123
      responses:
        "200":
          description: Authentication success, the response body contains a token pair.
          content:
            application/json:
              schema:
                allOf:
                  - type: object
                    required:
                      - meta
                    properties:
                      meta:
                        $ref: "#/components/schemas/RequestMeta"
                  - $ref: "#/components/schemas/TokenPair"
        "400":
          description: Authentication failure, either the username or the password were invalid.
          content:
            application/json:
              schema:
                required:
                  - meta
                  - code
                type: object
                properties:
                  meta:
                    $ref: "#/components/schemas/RequestMeta"
                  code:
                    type: string
                    enum:
                      - ERR_AUTHENTICATION
    put:
      security: []
      tags:
        - Auth
      summary: Retrieves a new token pair from the current login session data.
      description: Retrieves a new token pair using the refresh token from the previous pair.
      parameters:
        - in: query
          name: refresh
          schema:
            type: string
            format: sha256
            example: 2cf24dba5fb0a30e26e83b2ac5b9e29e1b161e5c1fa7425e73043362938b9825
          description: Refresh token from the current token pair.
      responses:
        "200":
          description: Authorization success, the response body contains a new token pair.
          content:
            application/json:
              schema:
                allOf:
                  - type: object
                    required:
                      - meta
                    properties:
                      meta:
                        $ref: "#/components/schemas/RequestMeta"
                  - $ref: "#/components/schemas/TokenPair"
        "400":
          description: Authorization failed, the refresh token was invalid.
          content:
            application/json:
              schema:
                required:
                  - meta
                  - code
                type: object
                properties:
                  meta:
                    $ref: "#/components/schemas/RequestMeta"
                  code:
                    type: string
                    enum:
                      - ERR_AUTHENTICATION
        "403":
          description: Authorization failed, the refresh token was already used. Clearly communicate to the user that their account credentials might be compromised.
          content:
            application/json:
              schema:
                required:
                  - meta
                  - code
                type: object
                properties:
                  meta:
                    $ref: "#/components/schemas/RequestMeta"
                  code:
                    type: string
                    enum:
                      - ERR_AUTHENTICATION
    delete:
      security: []
      tags:
        - Auth
      summary: Invalidate the current refresh token.
      description: Invalidates the current refresh token of the token pair, resulting in token pair invalidation once the access token expires.
      parameters:
        - in: query
          name: refresh
          schema:
            type: string
            format: sha256
            example: 2cf24dba5fb0a30e26e83b2ac5b9e29e1b161e5c1fa7425e73043362938b9825
          description: The refresh token to be invalidated.
      responses:
        "200":
          description: Token invalidation success. In a few minutes, the access token will become invalid as well, resulting in complete token pair invalidation.
          content:
            application/json:
              schema:
                allOf:
                  - type: object
                    properties:
                      meta:
                        $ref: "#/components/schemas/RequestMeta"
                  - type: object
                    required:
                      - code
                    properties:
                      code:
                        type: string
                        enum:
                          - SUCCESS
        "400":
          description: The refresh token was invalid, may be treated equally as the 200 response.
          content:
            application/json:
              schema:
                required:
                  - meta
                  - code
                type: object
                properties:
                  meta:
                    $ref: "#/components/schemas/RequestMeta"
                  code:
                    type: string
                    enum:
                      - ERR_AUTHENTICATION
  /login:
    get:
      tags:
        - Public routes
      summary: User-friendly HTML page for sign-in into data-review app.
      description: Returns a user-friendly HTML page with login input.
      responses:
        "200":
          description: The request was successful, the HTML body contain an HTML page.
  /me:
    get:
      tags:
        - Public routes
      summary: User-friendly HTML page for data review.
      description: Returns a user-friendly HTML page with details about the user of which the token has been issued to.
      responses:
        "200":
          description: Authorization success, the response body contains an HTML page.
        "401":
          description: The client's access token is either expired or non-existent. The HTML body contains a user-friendly HTML page with links back to login.
